trigger:
- master

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'smarthotelacr'
  imageRepository: 'bootcamp-demo'
  containerRegistry: 'smarthotelacr.azurecr.io'
  dockerfilePath: '**/app/Dockerfile'
  buildContext: 'app/'
  tag: '$(Build.BuildId)'

  imagePullSecret: 'smarthotelacr'
  
  # Kubernetes Namespace
  aksk8sNamespace: 'aks'
  eksk8sNamespace: 'eks'
  openshiftproject: 'openshiftproject'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        buildContext: $(buildContext)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'manifests'
        targetPath: 'manifests'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment:
    displayName: Deploy to AKS
    pool:
      vmImage: $(vmImageName)
    environment: SmartHotel360.aks-smarthotel-build-2019
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@1
            inputs:
              artifactName: 'manifests'
              downloadPath: '$(System.ArtifactsDirectory)/manifests'
              
          - script: kubectl delete suggestions -n aks

          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              namespace: $(aksk8sNamespace)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
          
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              namespace: $(aksk8sNamespace)
              manifests: |
                $(System.ArtifactsDirectory)/manifests/bootcamp-demo-deployment.yml
                $(System.ArtifactsDirectory)/manifests/bootcamp-demo-service.yml
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)
              imagePullSecrets: |
                $(imagePullSecret)

  - deployment:
    displayName: Deploy to EKS
    pool:
      vmImage: $(vmImageName)
    environment: SmartHotel360.eks-smarthotel-build-2019
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@1
            inputs:
              artifactName: 'manifests'
              downloadPath: '$(System.ArtifactsDirectory)/manifests'

          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              namespace: $(eksk8sNamespace)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
              
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              namespace: $(eksk8sNamespace)
              manifests: |
                $(System.ArtifactsDirectory)/manifests/bootcamp-demo-deployment.yml
                $(System.ArtifactsDirectory)/manifests/bootcamp-demo-service.yml
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)
              imagePullSecrets: |
                $(imagePullSecret)
  - deployment:
    displayName: Deploy to OpenShift
    pool:
      vmImage: $(vmImageName)
    environment: SmartHotel360.openshiftproject-smarthotel-build-2019
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@1
            inputs:
              artifactName: 'manifests'
              downloadPath: '$(System.ArtifactsDirectory)/manifests'

          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              namespace: $(openshiftproject)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
              
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              namespace: $(openshiftproject)
              manifests: |
                $(System.ArtifactsDirectory)/manifests/bootcamp-demo-deployment.yml
                $(System.ArtifactsDirectory)/manifests/bootcamp-demo-service.yml
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)
              imagePullSecrets: |
                $(imagePullSecret)
